<?php

use frontend\models\Tasks;

return [
  [
    'id' => 1,
    'title' => 'create bot',
    'address' => 'Moscow kievsky railway station',
    'created_at' => '2020-01-05 15:35:16',
    'budget' => 10000,
    'city_id' => 1,
    'lan' => 55.743108,
    'long' => 37.56629,
    'description' => 'Ullam ut sed amet officiis error aut ea. Soluta perferendis accusamus quisquam.',
    'category_id' => 2,
    'author_id' => 2,
    'performer_id' => null,
    'status' => Tasks::STATUS_NEW
  ],
  [
    'id' => 2,
    'title' => 'create bot',
    'address' => 'Moscow kievsky railway station',
    'created_at' => '2020-02-05 15:35:16',
    'budget' => 10000,
    'city_id' => 1,
    'lan' => 55.743108,
    'long' => 37.56629,
    'description' => 'Ullam ut sed amet officiis error aut ea. Soluta perferendis accusamus quisquam.',
    'category_id' => 2,
    'author_id' => 2,
    'performer_id' => 1,
    'status' => Tasks::STATUS_COMPLETED
  ],
  [
    'title' => 'create bot',
    'address' => 'Moscow kievsky railway station',
    'created_at' => '2020-02-05 15:35:16',
    'budget' => 10000,
    'city_id' => 1,
    'lan' => 55.743108,
    'long' => 37.56629,
    'description' => 'Ullam ut sed amet officiis error aut ea. Soluta perferendis accusamus quisquam.',
    'category_id' => 2,
    'author_id' => 2,
    'performer_id' => 1,
    'status' => Tasks::STATUS_NEW
  ],
  [
    'title' => 'create bot',
    'address' => 'Moscow kievsky railway station',
    'created_at' => '2020-02-05 15:35:16',
    'budget' => 10000,
    'city_id' => 1,
    'lan' => 55.743108,
    'long' => 37.56629,
    'description' => 'Ullam ut sed amet officiis error aut ea. Soluta perferendis accusamus quisquam.',
    'category_id' => 2,
    'author_id' => 2,
    'performer_id' => 9,
    'status' => Tasks::STATUS_NEW
  ],
  [
    'title' => 'create bot',
    'address' => 'Moscow kievsky railway station',
    'created_at' => '2020-02-05 15:35:16',
    'budget' => 10000,
    'city_id' => 1,
    'lan' => 55.743108,
    'long' => 37.56629,
    'description' => 'Ullam ut sed amet officiis error aut ea. Soluta perferendis accusamus quisquam.',
    'category_id' => 2,
    'author_id' => 2,
    'performer_id' => 6,
    'status' => Tasks::STATUS_NEW
  ],
  [
    'title' => 'create bot',
    'address' => 'Moscow kievsky railway station',
    'created_at' => '2020-02-05 15:35:16',
    'budget' => 10000,
    'city_id' => 1,
    'lan' => 55.743108,
    'long' => 37.56629,
    'description' => 'Ullam ut sed amet officiis error aut ea. Soluta perferendis accusamus quisquam.',
    'category_id' => 2,
    'author_id' => 2,
    'performer_id' => 3,
    'status' => Tasks::STATUS_NEW
  ],
  [
    'title' => 'create bot',
    'address' => 'Moscow kievsky railway station',
    'created_at' => '2020-02-05 15:35:16',
    'budget' => 10000,
    'city_id' => 1,
    'lan' => 55.743108,
    'long' => 37.56629,
    'description' => 'Ullam ut sed amet officiis error aut ea. Soluta perferendis accusamus quisquam.',
    'category_id' => 2,
    'author_id' => 2,
    'performer_id' => 1,
    'status' => Tasks::STATUS_NEW
  ],
  [
    'title' => 'create bot',
    'address' => 'Moscow kievsky railway station',
    'created_at' => '2020-02-05 15:35:16',
    'budget' => 10000,
    'city_id' => 1,
    'lan' => 55.743108,
    'long' => 37.56629,
    'description' => 'Ullam ut sed amet officiis error aut ea. Soluta perferendis accusamus quisquam.',
    'category_id' => 2,
    'author_id' => 2,
    'performer_id' => 1,
    'status' => Tasks::STATUS_NEW
  ],
  [
    'title' => 'create bot',
    'address' => 'Moscow kievsky railway station',
    'created_at' => '2020-02-05 15:35:16',
    'budget' => 10000,
    'city_id' => 1,
    'lan' => 55.743108,
    'long' => 37.56629,
    'description' => 'Ullam ut sed amet officiis error aut ea. Soluta perferendis accusamus quisquam.',
    'category_id' => 2,
    'author_id' => 2,
    'performer_id' => 1,
    'status' => Tasks::STATUS_NEW
  ],
  [
    'title' => 'create bot',
    'address' => 'Moscow kievsky railway station',
    'created_at' => '2020-02-05 15:35:16',
    'budget' => 10000,
    'city_id' => 1,
    'lan' => 55.743108,
    'long' => 37.56629,
    'description' => 'Ullam ut sed amet officiis error aut ea. Soluta perferendis accusamus quisquam.',
    'category_id' => 2,
    'author_id' => 2,
    'performer_id' => 1,
    'status' => Tasks::STATUS_NEW
  ],
  [
    'title' => 'create bot',
    'address' => 'Moscow kievsky railway station',
    'created_at' => '2020-02-05 15:35:16',
    'budget' => 10000,
    'city_id' => 1,
    'lan' => 55.743108,
    'long' => 37.56629,
    'description' => 'Ullam ut sed amet officiis error aut ea. Soluta perferendis accusamus quisquam.',
    'category_id' => 2,
    'author_id' => 2,
    'performer_id' => 1,
    'status' => Tasks::STATUS_NEW
  ],
  [
    'title' => 'create bot',
    'address' => 'Moscow kievsky railway station',
    'created_at' => '2020-02-05 15:35:16',
    'budget' => 10000,
    'city_id' => 1,
    'lan' => 55.743108,
    'long' => 37.56629,
    'description' => 'Ullam ut sed amet officiis error aut ea. Soluta perferendis accusamus quisquam.',
    'category_id' => 2,
    'author_id' => 2,
    'performer_id' => 5,
    'status' => Tasks::STATUS_NEW
  ],
  [
    'title' => 'create bot',
    'address' => 'Moscow kievsky railway station',
    'created_at' => '2020-02-05 15:35:16',
    'budget' => 10000,
    'city_id' => 1,
    'lan' => 55.743108,
    'long' => 37.56629,
    'description' => 'Ullam ut sed amet officiis error aut ea. Soluta perferendis accusamus quisquam.',
    'category_id' => 1,
    'author_id' => 2,
    'performer_id' => 4,
    'status' => Tasks::STATUS_NEW
  ],
];
